/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список предстоящих бронирований
         * @description Список предстоящих бронирований всех типов событий, отсортированный по start по возрастанию.
         *     По умолчанию возвращаются бронирования от текущего момента и далее.
         *     Если переданы оба параметра, требуется from <= to — иначе возвращается 400.
         */
        get: operations["adminListBookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/bookings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Удалить бронирование
         * @description Удалить бронирование по идентификатору.
         */
        delete: operations["adminDeleteBooking"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список типов событий
         * @description Получить все типы событий, созданные владельцем.
         */
        get: operations["adminListEventTypes"];
        put?: never;
        /**
         * Создать тип события
         * @description Создать новый тип события.
         */
        post: operations["adminCreateEventType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/event-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить тип события
         * @description Получить тип события по идентификатору.
         */
        get: operations["adminGetEventType"];
        put?: never;
        post?: never;
        /**
         * Удалить тип события
         * @description Удалить тип события. Существующие бронирования на этот тип события не удаляются.
         */
        delete: operations["adminDeleteEventType"];
        options?: never;
        head?: never;
        /**
         * Обновить тип события
         * @description Обновить произвольное подмножество полей типа события.
         */
        patch: operations["adminUpdateEventType"];
        trace?: never;
    };
    "/api/v1/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Создать бронирование
         * @description Создать бронирование на указанный слот.
         *
         *     Сервер проверяет, что start попадает в сетку слотов типа события, лежит в окне
         *     ближайших 14 дней и что интервал [start, start + durationMinutes) не пересекается
         *     ни с одним существующим бронированием (по любому типу события).
         *
         *     Несуществующий eventTypeId в теле запроса трактуется как бизнес-ошибка
         *     и возвращается как 422 с code="event_type_not_found", а не как 404.
         */
        post: operations["createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Публичный список типов событий
         * @description Публичный список типов событий, доступных гостю для записи.
         */
        get: operations["listEventTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/event-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Детали типа события
         * @description Детали типа события: название, описание, длительность.
         */
        get: operations["getEventType"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/event-types/{id}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Свободные слоты
         * @description Свободные слоты для выбранного типа события в окне ближайших 14 дней.
         *
         *     Шаг сетки равен durationMinutes типа события; возвращаются только незанятые
         *     интервалы с учётом всех бронирований по всем типам событий. Параметры from/to
         *     позволяют сузить диапазон, но должны укладываться в окно [now, now + 14 дней].
         */
        get: operations["listSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Созданное бронирование. */
        Booking: {
            /**
             * Format: uuid
             * @description Идентификатор бронирования.
             */
            readonly id: string;
            /**
             * Format: uuid
             * @description Идентификатор типа события, к которому относится бронирование.
             */
            eventTypeId: string;
            /** @description Название типа события, денормализовано для удобного отображения в админском списке. */
            eventTypeName: string;
            /**
             * Format: date-time
             * @description Начало бронирования (UTC).
             */
            start: string;
            /**
             * Format: date-time
             * @description Конец бронирования (UTC). Равен start + durationMinutes типа события.
             */
            end: string;
            /** @description Имя гостя. */
            guestName: string;
            /**
             * Format: email
             * @description Email гостя.
             */
            guestEmail: string;
            /** @description Заметка от гостя, если была предоставлена. */
            notes?: string;
            /**
             * Format: date-time
             * @description Момент создания бронирования (UTC).
             */
            readonly createdAt: string;
        };
        /** @description Тело запроса на создание бронирования гостем. */
        BookingCreate: {
            /**
             * Format: uuid
             * @description Идентификатор выбранного гостем типа события.
             */
            eventTypeId: string;
            /**
             * Format: date-time
             * @description Начало бронирования (UTC). Должно совпадать со start одного из свободных слотов,
             *     возвращённых GET /event-types/{id}/slots на момент запроса.
             */
            start: string;
            /** @description Имя гостя. */
            guestName: string;
            /**
             * Format: email
             * @description Email гостя — используется для подтверждения встречи.
             */
            guestEmail: string;
            /** @description Опциональная заметка от гостя (повестка, пожелания). */
            notes?: string;
        };
        /** @description Тип события, которым владеет единственный предопределённый владелец календаря. */
        EventType: {
            /**
             * Format: uuid
             * @description Идентификатор типа события.
             */
            readonly id: string;
            /** @description Краткое название типа события, показывается гостю. */
            name: string;
            /** @description Подробное описание — опционально. */
            description?: string;
            /**
             * Format: int32
             * @description Длительность события в минутах. Одновременно определяет шаг сетки слотов:
             *     свободные слоты генерируются каждые durationMinutes минут в рабочих часах владельца.
             *     Должна быть кратна 5 — проверяется сервером на запись (ограничение не выражено в схеме JSON Schema).
             */
            durationMinutes: number;
        };
        /** @description Тело запроса на создание типа события. */
        EventTypeCreate: {
            /** @description Краткое название типа события, показывается гостю. */
            name: string;
            /** @description Подробное описание — опционально. */
            description?: string;
            /**
             * Format: int32
             * @description Длительность события в минутах. Одновременно определяет шаг сетки слотов:
             *     свободные слоты генерируются каждые durationMinutes минут в рабочих часах владельца.
             *     Должна быть кратна 5 — проверяется сервером на запись (ограничение не выражено в схеме JSON Schema).
             */
            durationMinutes: number;
        };
        /** @description Тело запроса на частичное обновление типа события. Все поля опциональны. */
        EventTypeUpdate: {
            /** @description Краткое название типа события, показывается гостю. */
            name?: string;
            /** @description Подробное описание — опционально. */
            description?: string;
            /**
             * Format: int32
             * @description Длительность события в минутах. Одновременно определяет шаг сетки слотов:
             *     свободные слоты генерируются каждые durationMinutes минут в рабочих часах владельца.
             *     Должна быть кратна 5 — проверяется сервером на запись (ограничение не выражено в схеме JSON Schema).
             */
            durationMinutes?: number;
        };
        /** @description Представление ошибки в формате RFC 7807 Problem Details. */
        Problem: {
            /** @description URI-идентификатор типа ошибки (необязательный). */
            type?: string;
            /** @description Краткое человекочитаемое название проблемы. */
            title: string;
            /**
             * Format: int32
             * @description HTTP-статус ответа, продублированный в теле.
             */
            status: number;
            /** @description Подробное описание конкретного случая ошибки. */
            detail?: string;
            /** @description Стабильный machine-readable код ошибки, пригодный для ветвления клиентом. */
            code?: string;
        };
        /** @description Свободный слот: интервал времени, на который гость может записаться. */
        Slot: {
            /**
             * Format: date-time
             * @description Начало слота (UTC). Кратно durationMinutes относительно начала рабочего дня владельца.
             */
            start: string;
            /**
             * Format: date-time
             * @description Конец слота (UTC). Равен start + durationMinutes типа события.
             */
            end: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    adminListBookings: {
        parameters: {
            query?: {
                /** @description Нижняя граница выборки (UTC). По умолчанию — текущий момент. */
                from?: string;
                /** @description Верхняя граница выборки (UTC). По умолчанию — без верхней границы. */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"][];
                };
            };
            /** @description Некорректный запрос: нарушен формат email, длительность вне допустимого диапазона и т.п. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    adminDeleteBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Ресурс не найден: отсутствует тип события или бронирование с указанным id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    adminListEventTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    adminCreateEventType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description Некорректный запрос: нарушен формат email, длительность вне допустимого диапазона и т.п. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    adminGetEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description Ресурс не найден: отсутствует тип события или бронирование с указанным id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    adminDeleteEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description There is no content to send for this request, but the headers may be useful. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Ресурс не найден: отсутствует тип события или бронирование с указанным id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    adminUpdateEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTypeUpdate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description Некорректный запрос: нарушен формат email, длительность вне допустимого диапазона и т.п. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Ресурс не найден: отсутствует тип события или бронирование с указанным id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    createBooking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description Некорректный запрос: нарушен формат email, длительность вне допустимого диапазона и т.п. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /**
             * @description Конфликт: запрошенный слот уже занят другим бронированием.
             *     Правило уникальности времени действует по всем типам событий одновременно.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /**
             * @description Запрос валиден синтаксически, но нарушает бизнес-инварианты:
             *     start лежит вне окна 14 дней или не совпадает ни с одним слотом сетки.
             */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listEventTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    getEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description Ресурс не найден: отсутствует тип события или бронирование с указанным id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listSlots: {
        parameters: {
            query?: {
                /** @description Начало диапазона (UTC). По умолчанию — текущий момент. */
                from?: string;
                /** @description Конец диапазона (UTC). По умолчанию — now + 14 дней. */
                to?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Slot"][];
                };
            };
            /** @description Некорректный запрос: нарушен формат email, длительность вне допустимого диапазона и т.п. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Ресурс не найден: отсутствует тип события или бронирование с указанным id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
